lbs:
   EmailFromAddress: lbs@example.org
   EmailServer: smtp.gmail.com
   EmailPort: 465
   EmailUser: myuser@gmail.com
   EmailPassword: secret
   DeleteLogAfterDays: 20
   LBSUrl: http://lbs.example.org
   Users:
     demo:
       Password: demo
       GitURL: https://github.com/myusername/
       # GitURL: /home/myuser/lbs/
       EmailToAddress: firstname.lastname@example.org
       Projects:
         # mono will resolve automatically to https://github.com/myusername/lbs-mono
         mono:
           monodevelop-opt:
             Distros: ["centos/6/amd64"]
           monodevelop-tarball:
             Distros: ["fedora/20/amd64", "debian/wheezy/amd64"]
           monodevelop-nightly:
             Branches: ["master", "monodevelop-5.1-branch", "monodevelop-5.0-branch"]
             Distros: ["fedora/20/amd64"]
         test:
           test:
             Distros: ["centos/6/amd64", "debian/wheezy/amd64", "fedora/rawhide/amd64", "ubuntu/trusty/amd64"]

   Machines:
       mybuild01.lbs.example.org: 10.0.3.2
       mybuild02.lbs.example.org: 10.0.3.3

