lbs:
   EmailFromAddress: lbs@example.org
   EmailServer: smtp.gmail.com
   EmailPort: 465
   EmailUser: myuser@gmail.com
   EmailPassword: secret
   SendEmailOnSuccess: False
   DeleteLogAfterDays: 20
   KeepMinimumLogs: 5
   DeletePackagesAfterDays: 4
   KeepMinimumPackages: 4
   ShowNumberOfFinishedJobs: 30
   # BuildingTimeout in seconds, will stop the build if no output from build script arrives within that time
   BuildingTimeout: 600
   LBSUrl: http://lbs.example.org
   DownloadUrl: http://download.lbs.example.org
   SSHContainerPath: /root/.sshcontainer
   Users:
     business:
       Password: demo
       GitURL: https://mygitlab.example.com/myusername/
       GitType: gitlab
       Secret: VeryLongAndUnexpectedRandomPassword871623487619234761234
       EmailToAddress: firstname.lastname@example.org
       Projects:
         sample:
           sample:
             Distros: ["centos/6/amd64"]
     demo:
       Password: demo
       GitURL: https://github.com/myusername/
       # GitURL: /home/myuser/lbs/
       EmailToAddress: firstname.lastname@example.org
       Projects:
         # mono will resolve automatically to https://github.com/myusername/lbs-mono
         mono:
           PublicKey: "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x4796B710919684AC"
           monodevelop-opt:
             Distros: ["centos/6/amd64"]
           monodevelop-tarball:
             Distros: ["fedora/20/amd64", "debian/wheezy/amd64"]
           monodevelop-nightly:
             Branches: ["master", "monodevelop-5.1-branch", "monodevelop-5.0-branch"]
             Distros: ["fedora/20/amd64"]
         test:
           test:
             Distros: ["centos/6/amd64", "debian/wheezy/amd64", "fedora/rawhide/amd64", "ubuntu/trusty/amd64"]

   Machines:
       # IP is resolved through DNS
       mybuild01.lbs.example.org: 
          type: lxc
          port: 2222
          cid: 10
          priority: 1
       mybuild02.lbs.example.org:
       mybuild03.lbs.example.org:
          type: docker

