lbs:
   EmailFromAddress: lbs@example.org
   EmailServer: smtp.gmail.com
   EmailPort: 465
   EmailUser: myuser@gmail.com
   EmailPassword: secret
   SendEmailOnSuccess: False
   DeleteLogAfterDays: 20
   KeepMinimumLogs: 5
   DeletePackagesAfterDays: 4
   KeepMinimumPackages: 4
   ShowNumberOfFinishedJobs: 30
   PublicKeyServer: "keyserver.ubuntu.com"
   # WaitForDatabase in seconds, if several jobs are waiting for the database
   WaitForDatabase: 30
   # BuildingTimeout in seconds, will stop the build if no output from build script arrives within that time
   BuildingTimeout: 600
   LBSUrl: http://lbs.example.org
   DownloadUrl: http://lbs.example.org
   SSHContainerPath: /etc/lightbuildserver/container
   SqliteFile: /var/lib/lightbuildserver/db/lightbuildserver.db
   #MysqlUser: lbs
   #MysqlPassword: "secret"
   #MysqlDatabase: lbs
   GitSrcPath: /var/lib/lightbuildserver/src
   LogsPath: /var/lib/lightbuildserver/logs
   ReposPath: /var/lib/lightbuildserver/repos
   TarballsPath: /var/lib/lightbuildserver/tarballs
   Users:
     business:
       Password: demo
       GitURL: https://mygitlab.example.com/myusername/
       GitType: gitlab
       Secret: VeryLongAndUnexpectedRandomPassword871623487619234761234
       EmailToAddress: firstname.lastname@example.org
       Projects:
         sample:
           sample:
             Distros: ["centos/7/amd64"]
     demo:
       Password: demo
       GitURL: https://github.com/tpokorra/
       EmailToAddress: firstname.lastname@example.org
       Projects:
         # mono will resolve automatically to https://github.com/tpokorra/lbs-mono. or use attribute GitProjectName
         # by default the master branch will be used, but you can specify another branch too
         mono:
           GitProjectName: mono
           GitBranchName: master
           UseLXC: False
           PublicKey: "0x4796B710919684AC"
           Packages:
             monodevelop-opt:
               Distros: ["centos/6/amd64"]
             monodevelop-tarball:
               Distros: ["fedora/20/amd64", "debian/wheezy/amd64"]
             monodevelop-nightly:
               DisplayOrderBranches: Descending
               Branches: ["monodevelop-5.1-branch", "monodevelop-5.0-branch"]
               Distros: ["fedora/20/amd64"]
         kolab:
           Packages:
             sync:
               # will build this package always on this static machine.
               Machine: kolabobstogithub.pokorra.de
         openpetra:
           UseDocker: False
           Packages:
             openpetranow-standalone:
               WindowsInstaller: true
               Branches: ["master", "20150909_release_2015-09"]
               Distros: ["centos/7/amd64"]
         lbs:
           lightbuildserver:
             UseDocker: False
             Distros: ["fedora/25/amd64", "centos/7/amd64"]
           lxc-scripts:
             Distros: ["ubuntu/xenial/amd64", "fedora/25/amd64", "centos/7/amd64"]
           docker-scripts:
             Distros: ["fedora/25/amd64", "centos/7/amd64"]
         test:
           testWithoutPkg:
             Distros: ["centos/7/amd64", "debian/jessie/amd64"]
           test:
             Distros: ["centos/5/i686", "centos/6/amd64", "centos/7/amd64", "debian/wheezy/amd64", "debian/jessie/amd64", "fedora/rawhide/amd64", "fedora/24/amd64", "fedora/25/amd64", "ubuntu/trusty/amd64", "ubuntu/xenial/amd64"]

   Machines:
       # IP is resolved through DNS
       mybuild01.lbs.example.org: 
          type: lxc
          port: 2222
          cid: 10
          priority: 1
          enabled: False
       #mybuild02.lbs.example.org:
       #mybuild03.lbs.example.org:
       #   type: docker

       # IP is resolved through DNS
       build01.localhost:
           type: lxc
           # if this build container is on the same host as the LBS application
           local: True
           cid: 5
       kolabobstogithub.pokorra.de:
           # static machines are not created, just started and stopped. are only used when specified in package
           static: True
           type: lxc
           cid: 60
