lbs:
   EmailFromAddress: lbs@example.org
   EmailServer: smtp.gmail.com
   EmailPort: 465
   EmailUser: myuser@gmail.com
   EmailPassword: secret
   SendEmailOnSuccess: False
   DeleteLogAfterDays: 20
   KeepMinimumLogs: 5
   DeletePackagesAfterDays: 4
   KeepMinimumPackages: 4
   ShowNumberOfFinishedJobs: 30
   PublicKeyServer: "keyserver.ubuntu.com"
   # WaitForDatabase in seconds, if several jobs are waiting for the database
   WaitForDatabase: 30
   # BuildingTimeout in seconds, will stop the build if no output from build script arrives within that time
   BuildingTimeout: 600
   LBSUrl: http://localhost:8000
   DownloadUrl: http://lbs.example.org
   SSHContainerPath: ../var/container
   SqliteFile: ../var/db.sqlite3
   MaxDebugLevel: 1
   GitSrcPath: ../var/src
   LogsPath: ../var/logs
   ReposPath: ../var/repos
   TarballsPath: ../var/tarballs
   Users:
     demo:
       Password: demo
       GitURL: https://github.com/tpokorra/
       EmailToAddress: firstname.lastname@example.org
       Projects:
         lbs:
           lxd-scripts:
             Distros: ["debian/buster/amd64", "fedora/34/amd64"]
           docker-scripts:
             Distros: ["debian/buster/amd64", "fedora/34/amd64"]

   Machines:
       testbuild01lxd.lbs.solidcharity.com:
          type: lxd
          port: 2222
          cid: 10
          priority: 1
          enabled: True
